K_step: 100
accumulate_grad_batches: 1
audio_num_mel_bins: 80
audio_sample_rate: 24000
base_config:
- usr/configs/popcs_ds_beta6.yaml
- usr/configs/midi/cascade/opencs/opencpop_statis.yaml
binarization_args:
  shuffle: false
  with_align: true
  with_f0: true
  with_f0cwt: true
  with_spk_embed: false
  with_txt: true
  with_wav: true
binarizer_cls: data_gen.singing.binarize.OpencpopBinarizer
binary_data_dir: data/binary/opencpop-midi-dp
check_val_every_n_epoch: 10
clip_grad_norm: 1
content_cond_steps: []
cwt_add_f0_loss: false
cwt_hidden_size: 128
cwt_layers: 2
cwt_loss: l1
cwt_std_scale: 0.8
datasets:
- popcs
debug: false
dec_ffn_kernel_size: 9
dec_layers: 4
decay_steps: 50000
decoder_type: fft
dict_dir: ''
diff_decoder_type: wavenet
diff_loss_type: l1
dilation_cycle_length: 4
dropout: 0.1
ds_workers: 4
dur_enc_hidden_stride_kernel:
- 0,2,3
- 0,2,3
- 0,1,3
dur_loss: mse
dur_predictor_kernel: 3
dur_predictor_layers: 5
enc_ffn_kernel_size: 9
enc_layers: 4
encoder_K: 8
encoder_type: fft
endless_ds: true
ffn_act: gelu
ffn_padding: SAME
fft_size: 512
fmax: 12000
fmin: 30
fs2_ckpt: ''
gaussian_start: true
gen_dir_name: ''
gen_tgt_spk_id: -1
hidden_size: 256
hop_size: 128
infer: false
keep_bins: 80
lambda_commit: 0.25
lambda_energy: 0.0
lambda_f0: 0.0
lambda_ph_dur: 1.0
lambda_sent_dur: 1.0
lambda_uv: 0.0
lambda_word_dur: 1.0
load_ckpt: ''
log_interval: 100
loud_norm: false
lr: 0.001
max_beta: 0.06
max_epochs: 1000
max_eval_sentences: 1
max_eval_tokens: 60000
max_frames: 8000
max_input_tokens: 1550
max_sentences: 48
max_tokens: 40000
max_updates: 160000
mel_loss: ssim:0.5|l1:0.5
mel_vmax: 1.5
mel_vmin: -6.0
min_level_db: -120
norm_type: gn
num_ckpt_keep: 3
num_heads: 2
num_sanity_val_steps: 1
num_spk: 1
num_test_samples: 0
num_valid_plots: 10
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
out_wav_norm: false
pe_ckpt: checkpoints/0102_xiaoma_pe
pe_enable: true
pitch_ar: false
pitch_enc_hidden_stride_kernel:
- 0,2,5
- 0,2,5
- 0,2,5
pitch_extractor: parselmouth
pitch_loss: l1
pitch_norm: log
pitch_type: frame
pre_align_args:
  allow_no_txt: false
  denoise: false
  forced_align: mfa
  txt_processor: zh_g2pM
  use_sox: true
  use_tone: false
pre_align_cls: data_gen.singing.pre_align.SingingPreAlign
predictor_dropout: 0.5
predictor_grad: 0.1
predictor_hidden: -1
predictor_kernel: 5
predictor_layers: 5
prenet_dropout: 0.5
prenet_hidden_size: 256
pretrain_fs_ckpt: ''
processed_data_dir: data/processed/popcs
profile_infer: false
raw_data_dir: data/raw/popcs
ref_norm_layer: bn
rel_pos: true
reset_phone_dict: true
residual_channels: 256
residual_layers: 20
save_best: false
save_ckpt: true
save_codes:
- configs
- modules
- tasks
- utils
- usr
save_f0: true
save_gt: false
schedule_type: linear
seed: 1234
sort_by_len: true
spec_max:
- -0.79453
- -0.81116
- -0.61631
- -0.30679
- -0.13863
- -0.050652
- -0.11563
- -0.10679
- -0.091068
- -0.062174
- -0.075302
- -0.072217
- -0.063815
- -0.073299
- 0.007361
- -0.072508
- -0.050234
- -0.16534
- -0.26928
- -0.20782
- -0.20823
- -0.11702
- -0.070128
- -0.065868
- -0.012675
- 0.0015121
- -0.089902
- -0.21392
- -0.23789
- -0.28922
- -0.30405
- -0.23029
- -0.22088
- -0.21542
- -0.29367
- -0.30137
- -0.38281
- -0.4359
- -0.28681
- -0.46855
- -0.57485
- -0.47022
- -0.54266
- -0.44848
- -0.6412
- -0.687
- -0.6486
- -0.76436
- -0.49971
- -0.71068
- -0.69724
- -0.61487
- -0.55843
- -0.69773
- -0.57502
- -0.70919
- -0.82431
- -0.84213
- -0.90431
- -0.8284
- -0.77945
- -0.82758
- -0.87699
- -1.0532
- -1.0766
- -1.1198
- -1.0185
- -0.98983
- -1.0001
- -1.0756
- -1.0024
- -1.0304
- -1.0579
- -1.0188
- -1.05
- -1.0842
- -1.0923
- -1.1223
- -1.2381
- -1.6467
spec_min:
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
- -6.0
spk_cond_steps: []
stop_token_weight: 5.0
task_cls: usr.diffsinger_task.DiffSingerMIDITask
test_ids: []
test_input_dir: ''
test_num: 0
test_prefixes:
- "popcs-\u8BF4\u6563\u5C31\u6563"
- "popcs-\u9690\u5F62\u7684\u7FC5\u8180"
test_set_name: test
timesteps: 100
train_set_name: train
use_denoise: false
use_energy_embed: false
use_gt_dur: false
use_gt_f0: false
use_midi: true
use_nsf: true
use_pitch_embed: false
use_pos_embed: true
use_spk_embed: false
use_spk_id: false
use_split_spk_id: false
use_uv: true
use_var_enc: false
val_check_interval: 2000
valid_num: 0
valid_set_name: valid
vocoder: vocoders.hifigan.HifiGAN
vocoder_ckpt: checkpoints/0109_hifigan_bigpopcs_hop128
warmup_updates: 2000
wav2spec_eps: 1e-6
weight_decay: 0
win_size: 512
work_dir: checkpoints/0228_opencpop_ds100_rel
